
# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '7:56 am'

# Site footer
footer:
#  text: 'a footer static text'
  copyright:
    notice: 'COPYRIGHT Â© {year} WOWCHEMY PROTO.'
#  license:
#    enable: true
#    allow_commercial: false
#    allow_derivatives: false
#    share_alike: true
  social:
    - type: email
      url: 'example@email'
    - type: github
      url: 'https://github.com/'
    - type: twitter
      url: 'https://twitter.com/'
    - type: linkedin
      url: 'https://www.linkedin.com/'
    - type: facebook
      url: 'https://www.facebook.com/'